import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import { getMyBills } from "../services/appointmentService";
import "./Bills.css";

const Bills = () => {
  const [bills, setBills] = useState([]);

  useEffect(() => {
    fetchBills();
  }, []);

  const fetchBills = async () => {
    try {
      const data = await getMyBills();

      console.log("Bills API Response:", data);

      setBills(Array.isArray(data) ? data : []);
    } catch (error) {
      toast.error("Failed to load bills");
    }
  };

  return (
    <div className="user-bills">
      <h1>My Bills</h1>

      {Array.isArray(bills) && bills.length === 0 ? (
        <div className="bill-card">
          <h3>No Bills Available</h3>
          <p>
            Your hospital bills will appear here once they are generated by the
            hospital.
          </p>
        </div>
      ) : (
        <table className="bill-table">
          <thead>
            <tr>
              <th>Invoice</th>
              <th>Doctor</th>
              <th>Total</th>
              <th>Payment</th>
              <th>Status</th>
            </tr>
          </thead>

          <tbody>
            {bills.map((bill) => (
              <tr key={bill._id}>
                <td>{bill.invoiceNumber}</td>

                <td>{bill.doctor?.fullName}</td>

                <td>₹ {bill.totalAmount}</td>

                <td>{bill.paymentMethod}</td>

                <td>{bill.paymentStatus}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default Bills;
