import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import { getMyBills } from "../services/appointmentService";
import "./Bills.css";
import axios from "axios";

const Bills = () => {
  const [bills, setBills] = useState([]);

  useEffect(() => {
    fetchBills();
  }, []);

  const previewInvoice = async (id) => {
    const token = localStorage.getItem("patientToken");

    const response = await axios.get(
      `https://hospital-mini-erp.onrender.com/api/patient-user/bill/${id}/pdf`,
      {
        responseType: "blob",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
    );

    const file = new Blob([response.data], {
      type: "application/pdf",
    });

    const url = URL.createObjectURL(file);

    window.open(url);
  };

  const downloadInvoice = async (id) => {
    const token = localStorage.getItem("patientToken");

    const response = await axios.get(
      `https://hospital-mini-erp.onrender.com/api/patient-user/bill/${id}/pdf`,
      {
        responseType: "blob",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
    );

    const url = URL.createObjectURL(new Blob([response.data]));

    const link = document.createElement("a");

    link.href = url;

    link.download = "Invoice.pdf";

    document.body.appendChild(link);

    link.click();

    link.remove();
  };

  const fetchBills = async () => {
    try {
      const data = await getMyBills();

      console.log("Bills API Response:", data);

      setBills(Array.isArray(data) ? data : []);
    } catch (error) {
      toast.error("Failed to load bills");
    }
  };

  return (
    <div className="user-bills">
      <h1>My Bills</h1>

      {Array.isArray(bills) && bills.length === 0 ? (
        <div className="bill-card">
          <h3>No Bills Available</h3>
          <p>
            Your hospital bills will appear here once they are generated by the
            hospital.
          </p>
        </div>
      ) : (
        <table className="bill-table">
          <thead>
            <tr>
              <th>Invoice</th>
              <th>Doctor</th>
              <th>Total</th>
              <th>Payment</th>
              <th>Status</th>
              <th>pdf</th>
            </tr>
          </thead>

          <tbody>
            {bills.map((bill) => (
              <tr key={bill._id}>
                <td>{bill.invoiceNumber}</td>

                <td>{bill.doctor?.fullName}</td>

                <td>₹ {bill.totalAmount}</td>

                <td>{bill.paymentMethod}</td>

                <td>{bill.paymentStatus}</td>

                <td>
                  <button
                    className="preview-btn"
                    onClick={() => previewInvoice(bill._id)}
                  >
                    👁 Preview
                  </button>

                  <button
                    className="download-btn"
                    onClick={() => downloadInvoice(bill._id)}
                  >
                    ⬇ Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default Bills;
